### ISSUE TITLE
GLUT callbacks

### ISSUE THREAD

**Issue by drobilla** [puglfork/pugl#7]
I suppose I'll use this organization to address fragmentation issues since, having done a ton of work on upstream lately and investigated most of the forks, I think some work needs to happen on both ends to resolve this mess, and forking from crap ancient versions isn't good for anyone.

Which brings me to GLUT callbacks.  This is by far the most dramatic API break upstream from when most of the forks happened.  The event way is much better in almost every way, and being somewhat compatible with a dead and kind of crappy API really wasn't worth it in retrospect, but still, code out there uses it.

However, it's pretty easy to implement this separately from the core, it was always just dispatching (X) events to callbacks under the hood anyway.  I'd be fine with adding such a header if it gets people closer to (or ideally literally on) upstream.  It may not be possible (or at least very nice) to _completely_ preserve the API, possibly the first parameter to `puglSetMotionFunc` and friends would be a `PuglGlutDispatcher` or some such thing instead of a `PuglView`, but the callbacks themselves could easily stay identical.

But this is only worth doing if there is any interest in actually getting code using old forks working on upstream (lack thereof is why I eventually removed it in the first place).

So, this is essentially a poll/request/offer.  I'll do the work to make that stuff work again if there's a project that will use it.

**Comment by ssj71** [comment]
Not sure I weigh anything in this discussion, but I just plan to refactor to the latest pugl API. I'm already on the newer event based system though so its much easier for me. I'll let the others chime in.
